version: '2'
services:
    nginx:
        #image: nginx:latest
        build: .
        volumes:
            - "./etc/nginx/conf.d:/etc/nginx/conf.d"
#            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
     #       - "./php:/etc/php/5.6/fpm/pool.d"
#            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:8000"
#            - "3000:443"
#        environment:
#            - NGINX_HOST=${NGINX_HOST}
        
        #command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' && docker-php-entrypoint php5.6-fpm"
        #command: /bin/bash -c "nginx -g 'daemon off;' && docker-php-entrypoint php5.6-fpm"
       # command: /bin/bash -c "nginx -g 'daemon off;' "
#        command: /bin/bash -c "php-fpm5.6"
#        restart: always
        tty: true
        depends_on:
            - redis
            - tomcat
           # - mysqldb
 
    redis:
        image: redis:latest
#        build: php5.6
#        volumes:
##            - "./etc/nginx/conf.d:/etc/nginx/conf.d"
###            - "./etc/ssl:/etc/ssl"
#            - "./web:/var/www/html"
##            - "./php:/etc/php/5.6/fpm/pool.d"
###            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
#        tty: true
##        ports:
##            - "8001:8001"
###            - "3000:443"
###        environment:
###            - NGINX_HOST=${NGINX_HOST}
##        
##        #command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' && docker-php-entrypoint php5.6-fpm"
##        #command: /bin/bash -c "nginx -g 'daemon off;' && docker-php-entrypoint php5.6-fpm"
##       # command: /bin/bash -c "nginx -g 'daemon off;' "
###        command: /bin/bash -c "php-fpm5.6"
##        restart: always
    tomcat:
        image: scpman/solr:4.6.0
        ports:
            - "8081:8080"
        tty: true
